cbv/basic_app/urls.py
from django.urls import path , re_path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('' , views.WorksiteView.as_view(), name = 'list'),
    path('<int:pk>/' , views.WorksiteDetailView.as_view(), name = 'detail'),
]

cbv/cbv/urls.py
from django.contrib import admin
from django.urls import path , include
from basic_app import views



urlpatterns = [
    path('admin/', admin.site.urls ),
    path('' , views.IndexView.as_view() , name = 'index'),
    path('basic_app/' , include('basic_app.urls' , namespace = 'basic_app'))
]

cbv/basic_app/models.py
from django.db import models

# Create your models here.
class Worksite(models.Model):
    name = models.CharField(max_length = 256)
    supervisor = models.CharField(max_length = 256)
    location = models.CharField(max_length = 256)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})

class Employee(models.Model):
    name = models.CharField(max_length = 256)
    age = models.PositiveIntegerField()
    worksite = models.ForeignKey(Worksite , related_name = 'employees',  on_delete=models.CASCADE,)
    def __str__(self):
        return self.name

cbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View , TemplateView ,ListView , DetailView
from . import models
# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'


    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = 'Basic Injection!'
        return context


class WorksiteView(ListView):
    context_object_name = 'sites'
    model = models.Worksite

class WorksiteDetailView(DetailView):
    context_object_name = 'sites_detail'
    model = models.Worksite
    template_name = "basic_app/worksite_detail.html"

cbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta charset="utf-8">
    <title>Base</title>
  </head>
  <body>

    <nav class = "navbar navbar-expand-lg navbar-light bg-light">
      <ul class = "navbar-nav mr-auto">
        <li><a class = "navbar-brand" href="{% url 'basic_app:list'%}">Workistes</a></li>
        <li><a class = "navbar-item" href="{% url 'admin:index'%}">Admin</a></li>
        <li><a class = "navbar-item" href="#"></a></li>
      </ul>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>
  </body>
</html>

cbv/basic_app/templates/basic_app/worksite_detail.html
{% extends "basic_app/basic_app_base.html"%}


{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to the Worksite Detail Page</h1>
  <h2>sites Details:</h2>
  <p>{{sites_detail.name}}</p>
  <p>supervisor: {{sites_detail.supervisor}}</p>
  <p>location: {{sites_detail.location}} </p>
  <h3>Employees:</h3>
   {% for employee in sites_detail.employees.all %}

    <p>{{employee.name}} who is {{employee.age}} years old </p>
    {% endfor %}

</div>

{% endblock %}

cbv/basic_app/templates/basic_app/worksite_list.html
{% extends "basic_app/basic_app_base.html"%}


{% block body_block %}
<h1>Welcome, Here is a list of the worksites!</h1>
  <ol>
    {% for worksite in sites %}
    <h2><li><a href="{{worksite.id}}/">{{worksite.name}}</a></li></h2>
    {% endfor %}
  </ol>


{% endblock %}

cbv/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta charset="utf-8">
    <title>Base</title>
  </head>
  <body>

    <nav class = "navbar navbar-expand-lg navbar-light bg-light">
      <ul class = "navbar-nav mr-auto">
        <li><a class = "navbar-brand" href="{% url 'basic_app:list'%}">Workistes</a></li>
        <li><a class = "navbar-item" href="{% url 'admin:index'%}">Admin</a></li>
        <li><a class = "navbar-item" href="#"></a></li>
      </ul>
    </nav>

    <div class="container">
      {% block body_block %}

        {% endblock %}
    </div>
  </body>
</html>

cbv/templates/index.html
{% extends "base.html" %}

{% block body_block %}

<div class="jumbotron">
  <h1>Home Page!</h1>

</div>
{% endblock %}